web/router.ex
# web/router.ex
defmodule ChatPhoenix.Router do
  use ChatPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # ブラウザの場合、ユーザーのトークンを設定
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Other scopes may use custom stacks.
  scope "/api", ChatPhoenix do
    pipe_through :api

    # メッセージ一覧取得(:index)
    get "/messages", MessageController, :index
  end

  scope "/", ChatPhoenix do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    #
    get "/hello", HelloController, :index
    # 登録画面表示(new)と登録処理(create)
    get  "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    # ログイン画面表示(new)、ログイン処理(create)、ログアウト処理(delete)
    get    "/login", SessionController, :new
    post   "/login", SessionController, :create
    delete "/login", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatPhoenix do
  #   pipe_through :api
  # end

  # ログインしている場合、user_tokenキーにユーザーのトークンを設定
  defp put_user_token(conn, _) do
    if logged_in?(conn) do
      token = Phoenix.Token.sign(conn, "user", current_user(conn).id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end
end

web/views/layout_view.ex
defmodule ChatPhoenix.LayoutView do
  use ChatPhoenix.Web, :view
end

web/templates/layout/app.html.eex
<!-- web/templates/layout/app.html.eex -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello ChatPhoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if logged_in?(@conn) do %>
              <li><%= link "ログアウト", to: session_path(@conn, :delete), method: :delete %></li>
            <% else %>
              <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
              <li><%= link "ユーザ登録", to: registration_path(@conn, :new) %></li>
              <li><%= link "ログイン", to: session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
    <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>